# permissions for end users to view udproutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: udproute-viewer-role
rules:
- apiGroups:
  - specs.smi-spec.io
  resources:
  - udproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - specs.smi-spec.io
  resources:
  - udproutes/status
  verbs:
  - get
