apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: smi-controller-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: smi-controller-proxy-role
subjects:
- kind: ServiceAccount
  name: '{{ include "smi-controller.serviceAccountName" . }}'
  namespace: '{{ default .Release.Namespace }}'
