apiVersion: split.smi-spec.io/v1alpha4
kind: TrafficSplit
metadata:
  name: ab-test
spec:
  service: website
  matches:
  - kind: HTTPRouteGroup
    apiGroup: specs.smi-spec.io
    name: ab-test
  backends:
  - service: website-v1
    weight: 0
  - service: website-v2
    weight: 100

---
apiVersion: specs.smi-spec.io/v1alpha4
kind: HTTPRouteGroup
metadata:
  name: ab-test
spec:
  matches:
  - name: metrics
    pathRegex: "/metrics"
    methods:
    - GET
    headers:
      x-debug: "1"
  - name: health
    pathRegex: "/ping"
    methods: ["*"]