name: Go

on:
  [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup Kubebuilder
      run: |
        os=$(go env GOOS)
        arch=$(go env GOARCH)

        # download kubebuilder and extract it to tmp
        curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.1.0/kubebuilder_linux_amd64 \
             -o /tmp/kubebuilder

        sudo mv /tmp/kubebuilder /usr/local/bin/kubebuilder
   
    - name: Check Kubebuilder can generate CRDs
      run: make manifests
    
    - name: Check Kubebuilder can generate deep copy objects
      run: make generate

    - name: Build
      run: go build -v ./...

    - name: Code Tests
      run: make test
    
  functional_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup Functional Tests
      run: |
        curl https://shipyard.run/install | bash
        shipyard run ./shipyard

    - name: Run Functional Tests
      run: |
        eval $(shipyard env)
        make functional_test